//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceInfo
    {
        public DeviceInfo()
        {
            this.Item_Acc = new HashSet<Item_Acc>();
            this.Item_CalAct = new HashSet<Item_CalAct>();
        }
    
        public int id { get; set; }
        public System.Guid AuthCode { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual ICollection<Item_Acc> Item_Acc { get; set; }
        public virtual ICollection<Item_CalAct> Item_CalAct { get; set; }
    }
}
