//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Areas.Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NCCUEntities : DbContext
    {
        public NCCUEntities()
            : base("name=NCCUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DeviceInfo> DeviceInfo { get; set; }
        public virtual DbSet<Experiment_Apply> Experiment_Apply { get; set; }
        public virtual DbSet<Experiment_Attribute> Experiment_Attribute { get; set; }
        public virtual DbSet<Experiment_Item> Experiment_Item { get; set; }
    }
}
