//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Areas.Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NCCUEntities : DbContext
    {
        public NCCUEntities()
            : base("name=NCCUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DeviceInfo> DeviceInfo { get; set; }
        public virtual DbSet<Experiment_Apply> Experiment_Apply { get; set; }
        public virtual DbSet<Experiment_Attribute> Experiment_Attribute { get; set; }
        public virtual DbSet<Experiment_Item> Experiment_Item { get; set; }
        public virtual DbSet<Item_Acc> Item_Acc { get; set; }
        public virtual DbSet<Item_CalAct> Item_CalAct { get; set; }
    }
}
